# References
# https://stackoverflow.com/a/73882805/12014838
# https://github.com/aricooperdavis/ViewRanger-POI-Editor/blob/bc18c8c2d904f9ec82558332ed7923567534dd27/.github/workflows/minify.yml#L4

name: Minify and deploy

on:
  push:
    branches: [ prod ]

jobs:
  minify-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "20"
      
      - name: Install CLI tools
        run: |
          npm install -g terser
          npm install -g html-minifier
          npm install -g csso-cli

      - name: Minify overwriting original files
        run: |
          for i in *.js **/**.js; do terser $i -o $i --compress --mangle --module; done
          for i in *.html **/**.html; do html-minifier $i -o $i --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --collapse-boolean-attributes --minify-urls --remove-attribute-quotes --remove-empty-attributes --remove-style-link-type-attributes --minify-css --minify-js; done
          for i in *.css **/**.css; do csso $i -o $i; done

      - name: Push changes to test branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "Automated minification and deployment of ${{ github.sha }}"
          git push --force -u origin prod:test
