name: Minify and deploy

on:
  push:
    branches: [ live ]

jobs:
  minify-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Install NodeJS
        uses: actions/setup-node@main
        with:
          node-version: "20"
      
      - name: Install CLI tools
        run: |
          npm install -g html-minifier
          npm install -g lightningcss-cli
          npm install -g terser

      - name: Minify overwriting original files
        run: |
          find . -name "*.html" -exec html-minifier {} -o {} --collapse-whitespace --remove-comments --remove-redundant-attributes --remove-script-type-attributes --use-short-doctype --collapse-boolean-attributes --remove-empty-attributes --remove-style-link-type-attributes --minify-css --minify-js \;
          find . -name "*.css" -exec lightningcss -m {} -o {} \;
          find . -name "*.js" -exec terser {} -o {} --compress --mangle \;

      - name: Push changes to "live-min" branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "Automated minification and deployment of ${{ github.sha }}"
          git push --force -u origin live:live-min

      - name: Purge Cloudflare cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/695e9b8ac40b9d3c7274284cd5f4650f/purge_cache" -H "X-Auth-Email: ${{ SECRETS.EMAIL_GUI }}" -H "Authorization: Bearer ${{ SECRETS.CLOUDFLARE_PURGE_CACHE }}" -H "Content-Type: application/json" --data '{"files": ["https://guiruggiero.com/index.html", "https://guiruggiero.com/styles/*", "https://guiruggiero.com/modules/*"]}'
